backup/urls.py
from django.urls import path

from . import views

app_name = "backup"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("backup/", views.backup_view, name="backup"),
    path("restore/", views.restore_view, name="restore"),
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path("list/", views.list_view, name="list"),
    path("create/", views.create_view, name="create"),
    path("edit/<slug>/", views.edit_view, name="edit"),
    path("archive/<slug>/", views.archive_view, name="archive"),
    path("delete/<slug>/", views.delete_view, name="delete"),
]

timers/urls.py
from django.urls import path

from . import views

app_name = "timers"

urlpatterns = [
    path("list/", views.list_view, name="list"),
    path("edit/<int:id>/", views.edit_view, name="edit"),
    path("create/", views.create_view, name="create"),
    path("delete/<int:id>/", views.delete_view, name="delete"),
    path("stop/<int:id>/", views.stop_view, name="stop"),
    path("start/<slug>/", views.start_view, name="start"),
]

timetrack/urls.py
from django.contrib import admin
from django.urls import path, include

from projects import views as project_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("timers/", include("timers.urls")),
    path("reports/", include("reports.urls")),
    path("control-panel/", include("control_panel.urls")),
    path("", project_views.list_view),
]

projects/models.py
from datetime import datetime

from django.db import models

from django.contrib.auth.models import User

# Create your models here.


class Project(models.Model):
    class Meta:
        unique_together = ("slug", "user")

    name = models.CharField(max_length=64)
    slug = models.SlugField()
    description = models.CharField(max_length=255, blank=True)

    archived = models.BooleanField(default=False)
    favorite = models.BooleanField(default=False)

    user = models.ForeignKey(User, default=None, on_delete="CASCADE")

    created = models.DateTimeField(default=datetime.now)
    last_updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    @property
    def last_used(self):
        candidates = [t.start for t in self.timer_set.all()]
        if not candidates:
            return None

        return max(candidates).date()

projects/forms.py
from django import forms

from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "slug", "description"]


class ProjectEditForm(ProjectForm):
    class Meta(ProjectForm.Meta):
        fields = ProjectForm.Meta.fields + ["archived", "favorite"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = getattr(self, "instance", None)
        if instance and instance.id:
            self.fields["slug"].widget.attrs["readonly"] = True

    def clean_slug(self):
        instance = getattr(self, "instance", None)
        if instance and instance.id:
            return instance.slug
        else:
            return self.cleaned_data["slug"]

projects/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

import timers.services

from timetrack import theme

from .forms import ProjectForm, ProjectEditForm
from .models import Project
from .selectors import get_project, has_projects, projects_for_user

# Create your views here.


@login_required(login_url="/accounts/login")
def list_view(request):

    if not has_projects(user=request.user):
        return redirect("projects:create")

    archived = "archived" in request.GET
    projects = projects_for_user(user=request.user, archived=archived)

    # Get the active timer to display the card
    active = timers.services.get_active_timer(request.user)

    return render(
        request,
        "projects/list.html",
        theme.apply({"projects": projects, "timer": active}),
    )


@login_required(login_url="/accounts/login")
def create_view(request):

    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return redirect("projects:list")
    else:
        form = ProjectForm()
    return render(request, "projects/create.html", theme.apply({"form": form}))


@login_required(login_url="/accounts/login")
def edit_view(request, slug):

    instance = get_project(user=request.user, slug=slug)

    if request.method == "POST":
        form = ProjectEditForm(instance=instance, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("projects:list")
    else:
        form = ProjectEditForm(instance=instance)
    return render(
        request, "projects/edit.html", theme.apply({"form": form, "project": instance})
    )


@login_required
def archive_view(request, slug):
    if request.method == "POST":
        instance = get_project(user=request.user, slug=slug)
        instance.archived = not instance.archived
        instance.save()

        if "next" in request.POST:
            return redirect(request.POST.get("next"))
    return redirect("projects:list")


@login_required(login_url="/accounts/login")
def delete_view(request, slug):
    if request.method == "POST":
        get_project(user=request.user, slug=slug).delete()

        if "next" in request.POST:
            return redirect(request.POST.get("next"))
    return redirect("projects:list")

projects/templates/projects/create.html
{% extends 'base.html' %}
{% load materializecss %}
{% block content %}

    <div class="section">
        <div class="card">
            <form class="site-form" action="{% url 'projects:create' %}" method="post">
                <div class="card-content">
                    <span class="card-title">Create Project</span>
                    <button class="btn-floating halfway-fab waves-effect waves-light {{ colors.primary }}" type="submit" name="action">
                        <i class="material-icons">create</i>
                    </button>
                      {% csrf_token %}
                      {{ form | materializecss }}
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="/static/slugify.js"></script>
{% endblock %}

projects/templates/projects/edit.html
{% extends 'base.html' %}
{% load materializecss %}
{% block content %}

<div class="section">
    <div class="card">
        <form class="site-form" action="{% url 'projects:edit' slug=project.slug %}" method="post">
            <div class="card-content">
                <span class="card-title">Create Project</span>
                <button class="btn-floating halfway-fab waves-effect waves-light {{ colors.primary }}" type="submit" name="action">
                    <i class="material-icons">edit</i>
                </button>
                  {% csrf_token %}
                  {{ form | materializecss }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

projects/templates/projects/list.html
{% extends "base.html" %}
{% include materializecss %}

{% block fab %}
    {% if user.is_authenticated %}
    <div class="fixed-action-btn">
        <a href="{% url 'projects:create' %}" class="btn-floating btn-large {{ colors.primary }}"><i class="large material-icons">add</i></a>
    </div>
    {% endif %}
{% endblock %}

{% block content %}

    {% if timer %}
    <div class="section">
        {% include "timers/timer_card.html" %}
    </div>
    {% endif %}

    <div class="section">
        <table class="striped">
            <thead>
                <tr>
                    <th>Project</th>
                    <th class="hide-on-small-only">Description</th>
                    <th class="hide-on-med-and-down">Last Used</th>
                    <th class="center-align">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for project in projects %}
                <tr>
                    <td>{{ project.name }}</td>
                    <td class="hide-on-small-only">{{ project.description }}</td>
                    <td class="hide-on-med-and-down">{{ project.last_used }}</td>
                    <td class="right-align">
                        {% if not project.last_used %}
                        <form action="{% url 'projects:delete' slug=project.slug %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button class="btn-flat wave-effect {{ colors.secondary_text }}"><i class="material-icons">delete</i></button>
                            <input type="hidden" name="next" value="{{ request.path }}" />
                        </form>
                        {% else %}
                        <form action="{% url 'projects:archive' slug=project.slug %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button class="btn-flat wave-effect {{ colors.secondary_text }}">
                                {% if project.archived %}
                                <i class="material-icons">unarchive</i>
                                {% else %}
                                <i class="material-icons">archive</i>
                                {% endif %}
                            </button>
                            <input type="hidden" name="next" value="{{ request.path }}?{{ request.GET.urlencode }}" />
                        </form>
                        {% endif %}
                        <a href="{% url 'projects:edit' slug=project.slug %}" class="btn-flat"><i class="material-icons {{ colors.secondary_text }}">mode_edit</i></a>
                        <form action="{% url 'timers:start' slug=project.slug %}" method="POST" style="display:inline;">
                            {% csrf_token %}
                            <button class="btn-flat wave-effect {{ colors.primary_text }} {% if timer %} disabled {% endif %}" action="submit"><i class="material-icons">play_arrow</i></button>
                            <input type="hidden" name="next" value="{{ request.path }}" />
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>


        <div class="section">
        {% if "archived" not in request.GET %}
            <a href="{% url 'projects:list' %}?archived" class="btn {{ colors.secondary }}">Archived</a>
        {% else %}
            <a href="{% url 'projects:list' %}" class="btn {{ colors.secondary }}">Back</a>
        {% endif %}
        </div>


    </div>
{% endblock %}