accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register_view, name="register"),
]

backup/urls.py
from django.urls import path

from . import views

app_name = "backup"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("backup/", views.backup_view, name="backup"),
    path("restore/", views.restore_view, name="restore"),
]

projects/urls.py
from django.urls import path

from . import views

app_name = "projects"

urlpatterns = [
    path("list/", views.list_view, name="list"),
    path("create/", views.create_view, name="create"),
    path("edit/<slug>/", views.edit_view, name="edit"),
    path("archive/<slug>/", views.archive_view, name="archive"),
    path("delete/<slug>/", views.delete_view, name="delete"),
]

reports/urls.py
from django.urls import path

from . import views

app_name = "reports"

urlpatterns = [
    path("day/", views.view_day, name="day"),
    path("week/", views.view_week, name="week"),
    path("month/", views.view_month, name="month"),
]

timers/urls.py
from django.urls import path

from . import views

app_name = "timers"

urlpatterns = [
    path("list/", views.list_view, name="list"),
    path("edit/<int:id>/", views.edit_view, name="edit"),
    path("create/", views.create_view, name="create"),
    path("delete/<int:id>/", views.delete_view, name="delete"),
    path("stop/<int:id>/", views.stop_view, name="stop"),
    path("start/<slug>/", views.start_view, name="start"),
]

timetrack/urls.py
from django.contrib import admin
from django.urls import path, include

from projects import views as project_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("timers/", include("timers.urls")),
    path("reports/", include("reports.urls")),
    path("control-panel/", include("control_panel.urls")),
    path("", project_views.list_view),
]

templates/base.html
{% load static %}
<html>
    <head>

        <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <title>Timetrack 3</title>
    </head>
    <body>

        <header>
            <ul id="dropdown-reports" class="dropdown-content">
                <li><a href="{% url 'reports:day' %}">Day</a></li>
                <li><a href="{% url 'reports:week' %}">Week</a></li>
                <li><a href="{% url 'reports:month' %}">Month</a></li>
            </ul>

            <nav class="{{ colors.primary }}">
                <div class="nav-wrapper">
                    <a href="/" class="brand-logo"><img src="{% static 'timetrack_logo.png' %}" style="height: 100%;"/></a>

                    <a href="#" data-target="mobile-sidenav" class="sidenav-trigger"><i class="material-icons">menu</i></a>

                        <ul id="nav-main" class="right hide-on-med-and-down">
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'projects:list' %}">Projects</a></li>
                            <li><a href="{% url 'timers:list' %}">Timers</a></li>
                            <li><a class="dropdown-trigger" href="#!" data-target="dropdown-reports">Reports<i class="material-icons right">arrow_drop_down</i></a></li>
                            <li><a href="{% url 'control_panel:index' %}">Settings</a></li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            {% else %}
                            <li><a href="{% url 'accounts:login' %}">Login</a></li>
                            <li><a href="{% url 'accounts:register' %}">Register</a></li>
                            {% endif %}
                        </ul>
                    </form>

                </div>
            </nav>

            <ul class="sidenav" id="mobile-sidenav">
                {% if user.is_authenticated %}
                <li><a href="{% url 'projects:list' %}">Projects</a></li>
                <li><a href="{% url 'timers:list %'}">Timers</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'reports:day' %}">Daily Report</a></li>
                <li><a href="{% url 'reports:week' %}">Weekly Report</a></li>
                <li><a href="{% url 'reports:month' %}">Monthly Report</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'control_panel:index' %}">Settings</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:register' %}">Register</a></li>
                {% endif %}
            </ul>

            {% block fab %}
            {% endblock %}

        </header>

        <div class="container">

            <main>
{% block content %}
{% endblock %}
            </main>

            <footer>

            </footer>
        </div>

        <!--JavaScript at end of body for optimized loading-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.js"></script>
        <script>
            $(document).ready(function(){
                $(".dropdown-trigger").dropdown();
                $('.sidenav').sidenav();
                $('.fixed-action-btn').floatingActionButton();
                $('.datepicker').datepicker({"format": "yyyy-mm-dd"});
                $('.timepicker').timepicker({"format": "hh:mm:ss"});
                $('select').formSelect();
            });
        </script>
{% block scripts %}
{% endblock %}
    </body>
</html>