backup/urls.py
from django.urls import path

from . import views

app_name = "backup"

urlpatterns = [
    path("", views.index_view, name="index"),
    path("backup/", views.backup_view, name="backup"),
    path("restore/", views.restore_view, name="restore"),
]

timers/urls.py
from django.urls import path

from . import views

app_name = "timers"

urlpatterns = [
    path("list/", views.list_view, name="list"),
    path("edit/<int:id>/", views.edit_view, name="edit"),
    path("create/", views.create_view, name="create"),
    path("delete/<int:id>/", views.delete_view, name="delete"),
    path("stop/<int:id>/", views.stop_view, name="stop"),
    path("start/<slug>/", views.start_view, name="start"),
]

timetrack/urls.py
from django.contrib import admin
from django.urls import path, include

from projects import views as project_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("projects/", include("projects.urls")),
    path("timers/", include("timers.urls")),
    path("reports/", include("reports.urls")),
    path("control-panel/", include("control_panel.urls")),
    path("", project_views.list_view),
]

timers/models.py
from datetime import timedelta
import pendulum

from django.core.exceptions import ValidationError
from django.db.models import DateTimeField as BaseDateTimeField
from django.db import models

from projects.models import Project


class DateTimeField(BaseDateTimeField):
    def value_to_string(self, obj):
        val = self.value_from_object(obj)

        if isinstance(value, pendulum.DateTime):
            return value.format("YYYY-MM-DD HH:mm:ss")

        return "" if val is None else val.isoformat()


class Timer(models.Model):
    class Meta:
        unique_together = ("project", "start")

    project = models.ForeignKey(Project, on_delete="CASCADE")

    start = DateTimeField(default=pendulum.now)
    stop = DateTimeField(blank=True, null=True)

    @property
    def elapsed(self):
        if self.stop is not None:
            diff = self.stop - self.start
        else:
            diff = timedelta(seconds=(pendulum.now() - self.start).seconds)
        return diff - timedelta(microseconds=diff.microseconds)

    def __str__(self):
        return f"Timer[project: {self.project.name}, start: {self.start}]"

    def clean(self, *args, **kwargs):
        if self.start > pendulum.now():
            raise ValidationError("Start time in the future.")

        if self.start and self.stop:
            if self.stop < self.start:
                raise ValidationError("Stop time after start time.")

timers/forms.py
from django import forms

from .models import Timer
from .services import get_active_timer, clear_active_timer


class TimerForm(forms.ModelForm):
    class Meta:
        model = Timer
        fields = ["project", "start", "stop"]

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        active = get_active_timer(self.user)

        if active is not None and cleaned_data["stop"] is None:
            if active.start > cleaned_data["start"]:
                raise forms.ValidationError(
                    f"Cannot create active timer before {active.start}"
                )

        return cleaned_data

timers/views.py
from datetime import datetime, timezone

from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
import pendulum

from projects.models import Project

from timetrack import theme

from .forms import TimerForm
from .models import Timer
from . import services

# Create your views here.


@login_required(login_url="/accounts/login")
def list_view(request):
    timer_list = (
        Timer.objects.filter(project__user=request.user).order_by("-start").all()
    )
    page = request.GET.get("page", 1)

    paginator = Paginator(timer_list, 25)

    try:
        timers = paginator.page(page)
    except PageNotAnInteger:
        timers = paginator.page(1)
    except EmptyPage:
        timers = paginator.page(paginator.num_pages)

    return render(request, "timers/list.html", theme.apply({"timers": timers}))


@login_required(login_url="/accounts/login")
def edit_view(request, id):

    instance = Timer.objects.get(id=id)

    if request.method == "POST":
        form = TimerForm(user=request.user, instance=instance, data=request.POST)
        if form.is_valid():
            form.save()

            if "next" in request.POST:
                return redirect(request.POST.get("next"))

            return redirect("timers:list")
    else:
        form = TimerForm(user=request.user, instance=instance)
    return render(
        request, "timers/edit.html", theme.apply({"form": form, "timer": instance})
    )


@login_required(login_url="/accounts/login")
def create_view(request):

    if request.method == "POST":
        form = TimerForm(user=request.user, data=request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            active = services.get_active_timer(request.user)
            if active is not None and instance.start > active.start:
                active.stop = instance.start
                active.save()
            instance.save()

            if "next" in request.POST:
                return redirect(request.POST.get("next"))

            return redirect("timers:list")
    else:
        form = TimerForm(user=request.user)
    return render(request, "timers/create.html", theme.apply({"form": form}))


@login_required(login_url="/accounts/login")
def delete_view(request, id):
    if request.method == "POST":
        Timer.objects.get(id=id).delete()
        if "next" in request.POST:
            return redirect(request.POST.get("next"))

    return redirect("timers:list")


@login_required(login_url="/accounts/login")
def stop_view(request, id):
    if request.method == "POST":
        timer = Timer.objects.get(id=id)
        timer.stop = datetime.now(timezone.utc)
        timer.save()

        print(f"Got data {request.POST}")

        if "next" in request.POST:
            return redirect(request.POST.get("next"))

    return redirect("timers:list")


@login_required(login_url="/accounts/login")
def start_view(request, slug):
    if request.method == "POST":
        project = Project.objects.get(slug=slug)
        form = TimerForm(
            user=request.user,
            data={"project": project.id, "start": datetime.now(timezone.utc)},
        )

        if form.is_valid():
            form.save()

            if "next" in request.POST:
                return redirect(request.POST.get("next"))
            return redirect("timers:list")

    return redirect("timers:list")

timers/templates/timers/create.html
{% extends 'base.html' %}
{% load materializecss %}
{% block content %}

<div class="section">
    <div class="card">
        <form class="site-form" action="{% url 'timers:create' %}" method="post">
            <div class="card-content">
                <span class="card-title">Create Timer</span>
                <button class="btn-floating halfway-fab waves-effect waves-light {{ colors.primary }}" type="submit" name="action">
                    <i class="material-icons">edit</i>
                </button>
                  {% csrf_token %}
                  {% if form.non_field_errors %}
                  <div class="card {{ colors.primary }} {{ colors.light_text }}">
                      <div class="card-content">
                          <span class="card-title">Error</span>
                          <p>{{ form.non_field_errors }}</p>
                      </div>
                  </div>
                  {% endif %}

                  {{ form.non_field_errors }}
                  {{ form.project | materializecss }}
                  {{ form.start }}
                  {{ form.stop }}
                  <!-- Include the next target in the form data -->
                  {% if request.GET.next %}
                      <input type="hidden" name="next" value="{{ request.GET.next }}">
                  {% endif %}
            </div>
        </form>
    </div>
</div>

{% endblock %}

timers/templates/timers/edit.html
{% extends 'base.html' %}
{% load materializecss %}
{% block content %}

<div class="section">
    <div class="card">
        <form class="site-form" action="{% url 'timers:edit' id=timer.id %}" method="post">
            <div class="card-content">
                <span class="card-title">Edit Timer</span>
                <button class="btn-floating halfway-fab waves-effect waves-light {{ colors.primary }}" type="submit" name="action">
                    <i class="material-icons">edit</i>
                </button>
                  {% csrf_token %}
                  {% if form.non_field_errors %}
                  <div class="card {{ colors.primary }} {{ colors.light_text }}">
                      <div class="card-content">
                          <span class="card-title">Error</span>
                          <p>{{ form.non_field_errors }}</p>
                      </div>
                  </div>
                  {% endif %}
                  {{ form.project | materializecss }}
                  {{ form.start }}
                  {{ form.stop }}
                  <!-- Include the next target in the form data -->
                  {% if request.GET.next %}
                      <input type="hidden" name="next" value="{{ request.GET.next }}">
                  {% endif %}
            </div>
        </form>
        <form action="{% url 'timers:delete' id=timer.id %}", method="POST">
            {% csrf_token %}
            <button class="btn-flat {{ colors.primary_text }}" action="submit"><i class="material-icons">delete</i></button>
        </form>
    </div>
</div>

{% endblock %}

timers/templates/timers/list.html
{% extends 'base.html' %}

{% block fab %}
    {% if user.is_authenticated %}
    <div class="fixed-action-btn">
        <a href="{% url 'timers:create' %}" class="btn-floating btn-large {{ colors.primary }}"><i class="large material-icons">add</i></a>
    </div>
    {% endif %}
{% endblock %}

{% block content %}

    <div class="section">
        {% for timer in timers %}
        {% include "timers/timer_card.html" %}
        {% endfor %}
    </div>

    <div class="section">
        <div class="center">
            <!-- The order is reversed, so older is next, newer is previous -->
            {% if timers.has_next %}
            <a href="{{ request.path }}?page={{ timers.paginator.num_pages }}" class="btn {{ colors.secondary }}"><i class="material-icons">first_page</i></a>
            <a href="{{ request.path }}?page={{ timers.next_page_number }}" class="btn {{ colors.secondary }}"><i class="material-icons">chevron_left</i></a>

            {% else %}
            <a href="#" class="btn disabled"><i class="material-icons">first_page</i></a>
            <a href="#" class="btn disabled"><i class="material-icons">chevron_left</i></a>
            {% endif %}

            {% if timers.has_previous %}
            <a href="{{ request.path }}?page={{ timers.previous_page_number }}" class="btn {{ colors.secondary }}"><i class="material-icons">chevron_right</i></a>
            <a href="{{ request.path }}?page=1" class="btn {{ colors.secondary }}"><i class="material-icons">last_page</i></a>
            {% else %}
            <a href="#" class="btn disabled"><i class="material-icons">chevron_right</i></a>
            <a href="#" class="btn disabled"><i class="material-icons">last_page</i></a>
            {% endif %}
        </div>
        <div class="center">
            <label>Page {{ timers.number }} of {{ timers.paginator.num_pages }}</label>
        </div>
    </div>

{% endblock %}

timers/templates/timers/timer_card.html
<form action="{% url 'timers:stop' id=timer.id %}" method="POST">
    {% csrf_token %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ timer.project.name }}</span>
            <p class="float_text">{{ timer.project.description }}</p>
            <p class="float_text">Started at {{ timer.start }}</p>
            {% if timer.stop %}
            <p class="float_text">Stopped at {{ timer.stop }}</p>
            {% endif %}
        </div>
        <div class="card-action">
            <a href="{% url 'timers:edit' id=timer.id %}" class="btn-flat wave-effect {{ colors.secondary_text }} "><i class="material-icons">edit</i></a>
        </div>
        {% if not timer.stop %}
        <button class="btn-floating halfway-fab {{ colors.primary }} right"><i class="material-icons">stop</i></button>
        {% endif %}
    </div>
    <input type="hidden" name="next" value="{{ request.path }}">
</form>